title: Spencer Kenison
description: This is a basic website to introduce Spencer Kenison, his education, and experiences.
author: Spencer Kenison

collections:
  projects:
    output: true
    permalink: /projects/:name/
